### ISSUE TITLE
Include puppet lint and template checking on per file basis in the Guardfile

### ISSUE THREAD

**Issue by nikolavp** [garethr/puppet-module-skeleton#10]
Here is what I have in my Guardfiles for a while

```ruby
guard 'shell' do
  watch(/^manifests\/(.*).pp$/) {|m|
    status = `puppet-lint #{m[0]}`
    if !status.empty?
        puts "Problems for #{m[0]} found"
        puts status
    end
  }
  watch(/(.*).erb$/) {|m|
    status = `cat #{m[0]} | erb -x -T - | ruby -c > /dev/null`
    if $?.to_i != 0
        puts "Errors for #{m[0]}"
        puts status
    end
  }
end
```

This is just checking .erb and .pp files in the current directory. Add sub paths or any other tweaks as needed and keep up the good work!

-- 
Nikola

**Comment by garethr** [comment]
Puppet syntax is integrated with guard at this point and I think does the second part well. And Puppet lint is run whenever files change too. The only advantage I could see of the above was it acts on individual files, so would help during a refactoring of an old code base. So a useful example in some cases but not one I think worth adding to the skeleton. Thanks!

**Comment by nikolavp** [comment]
(y) makes sense
