### ISSUE TITLE
Could not find class

### ISSUE THREAD

**Issue by reppard** [garethr/puppet-module-skeleton#111]
Out of the box, if I generate the module and run 'rake spec' it can't find the class.  The init.pp is there with the class defined.  Am I missing something?

**Comment by garethr** [comment]
Can you provide the specific commands you're running and the output of each? Maybe throw in a few calls to `ls` or `tree`?

**Comment by reppard** [comment]
@garethr I think I've gotten it figured out.  I'm sorta new to test driving modules and neglected to run 'rspec-puppet-init'.  Thanks for the response!
