### ISSUE TITLE
Updated install.sh script not working

### ISSUE THREAD

**Issue by richburroughs** [garethr/puppet-module-skeleton#115]
I did a pull and saw the logic in the install.sh script that picks where to install the files had been updated. I ran the new install script but it didn't seem to work for me. I created a new module after and puppet used the default skeleton.

I'm using Puppet 4.3.2 installed as a gem.

Afterwards I tried the manual instructions:

`find skeleton -type f | git checkout-index --stdin --force --prefix="$HOME/.puppetlabs/opt/puppet/cache/puppet-module/" --
`

That did work. I made the new module again and it used this skeleton, not the default.

**Comment by richburroughs** [comment]
So it looks like the install script is putting the files into:

$HOME/.puppetlabs/opt/puppet/cache/puppet-moduleskeleton

The manual command (which works) it putting them into:

$HOME/.puppetlabs/opt/puppet/cache/puppet-module/

**Comment by richburroughs** [comment]
I can't explain how this is happening. Maybe this is just my weirdness but I was able to rm my .puppetlabs dir and duplicate it.

But I can't see where that path is coming from:

`(rich) puppet-module-skeleton(master) install_dir=$(puppet apply --configprint module_working_dir)
(rich) puppet-module-skeleton(master) echo $install_dir
/Users/richardb/.puppetlabs/opt/puppet/cache/puppet-module
`

That looks fine to me.

**Comment by richburroughs** [comment]
`(rich) puppet-module-skeleton(master) rm -rf ~/.puppetlabs
(rich) puppet-module-skeleton(master) ./install.sh
(rich) puppet-module-skeleton(master) ls -al ~/.puppetlabs/opt/puppet/cache
total 0
drwxr-xr-x   3 richardb  IUSA\Domain Users  102 Feb 25 15:48 .
drwxr-xr-x   3 richardb  IUSA\Domain Users  102 Feb 25 15:48 ..
drwxr-xr-x  21 richardb  IUSA\Domain Users  714 Feb 25 15:48 puppet-moduleskeleton
`

**Comment by richburroughs** [comment]
Ran it with "bash -x":

(rich) puppet-module-skeleton(master) ✗ ./install.sh
++ puppet apply --configprint module_working_dir
+ install_dir=/Users/richardb/.puppetlabs/opt/puppet/cache/puppet-module
+ find skeleton -type f -not -name .gitkeep
+ git checkout-index --stdin --force --prefix=/Users/richardb/.puppetlabs/opt/puppet/cache/puppet-module

**Comment by richburroughs** [comment]
Yeah that is not working. If I run those commands manually:

find skeleton -type f -not -name .gitkeep | git checkout-index --stdin --force --prefix=/Users/richardb/.puppetlabs/opt/puppet/cache/puppet-module

I get:

(rich) puppet-module-skeleton(master) ls -al ~/.puppetlabs/opt/puppet/cache
total 0
drwxr-xr-x   3 richardb  IUSA\Domain Users  102 Feb 25 15:55 .
drwxr-xr-x   3 richardb  IUSA\Domain Users  102 Feb 25 15:55 ..
drwxr-xr-x  21 richardb  IUSA\Domain Users  714 Feb 25 15:55 puppet-moduleskeleton

**Comment by binford2k** [comment]
Fixed in #113

**Comment by richburroughs** [comment]
Oh wow sorry. I looked at the issue list and didn't see that.
