### ISSUE TITLE
provide better samples for tests

### ISSUE THREAD

**Issue by igalic** [garethr/puppet-module-skeleton#18]
the puppetlabs team has had many a painful experience with how to test correctly. I think we should follow their lead and give good examples here.

acceptance tests
----------------------

it's not really useful to query if a package is installed or a service is running, we should be checking for the *impact* that we're having on the system, that it's reacting correctly to our configurations.

class & define tests
-------------------------

core functionality is tested here. whenever there's a decision in the code, we should have tests covering both sides. these tests are *easy* because they are fast.

We should promote the use of @apenney's [puppet_facts](https://github.com/apenney/puppet_facts) here, rather than the use of setting them manually with `let`

unit tests (for types, functions providers)
---------------------------------------------------

we could provide what looks like a healthy boilerplate examples without bloat. unfortunately I don't think we're quite there yet ;)

---

this is a wish-list for what I'd like to see testing to move to, generally, but yeah, we're not quite there yet. puppet_facts seems problematic from a FOSS perspective, because currently it's only populated with Puppet Enterprise facts (and one Ubuntu 14.04 machine provided by me). &c…

finally there's the general problem that tests in puppet aren't really useful from an explorative development point or design of view: they only start to become useful once we've got working code.
(maybe this is view of mine is ***wrong***, but if it isn't, then our community has a communication and documentation problem ;)

**Comment by garethr** [comment]
I'm going to close this for now. Happy to see suggested changes to the out-of-the-box tests, and they have changed a bunch since this issue was opened (rspec-puppet-facts is integrated for instance).
