### ISSUE TITLE
Supported Puppet/Ruby versions

### ISSUE THREAD

**Issue by shoekstra** [garethr/puppet-module-skeleton#35]
Hello,

Not so much an issue but more of a question: do we still need to have Ruby 1.8.7 and Puppet 2.7 tested?  If PL doesn't support the versions (2.7 has been EOL for a year now), should module writers?

Just wanted to put the question out there as I don't know if it's just me but I'm finding more often that some tests fail with Ruby 1.8.7 but pass newer versions, so I keep removing related references and wondered if others have the same experience and whether it's time it was removed from the skeleton?

**Comment by garethr** [comment]
I'm going to update the matrix soon, but after a discussion with a few users I've decided to leave 2.7 in, mainly due to lots of people still using it from system packages. If you're not using it you can obviously remove it for your individual modules.
