### ISSUE TITLE
Could not locate Gemfile

### ISSUE THREAD

**Issue by walidshaari** [garethr/puppet-module-skeleton#38]
new to both puppet and Ruby, trying your module-skeleton on puppet enterprise training vm, linux i386 got the following error after runing "puppet module generate usr-module;cd ./usr-module;bundle install"
copying  the Gemfile from /root/.puppet/var/puppet-module/skeleton/Gemfile seems to solve the problem, should i assume that should have been created during the module generation but have not? also using the system Centos6 bundle fails, but the puppet /opt/puppet/bin/bundle seems to work just fine until it hist g++ dependency.

**Comment by garethr** [comment]
Hi @walidshaari, just checking if you resolved this issue? I'll close it if so or if I don't hear back. Cheers.
