### ISSUE TITLE
Rake Task lint breaks with puppet-lint 1.1.0

### ISSUE THREAD

**Issue by rauchrob** [garethr/puppet-module-skeleton#45]
The puppet-lint configuration in Rakefile breaks with puppet-lint 1.1.0 - see the corresponding [issue](https://github.com/rodjek/puppet-lint/issues/355) for puppet-lint.

There is already a [workaround](https://github.com/rodjek/puppet-lint/issues/331) for puppet-lint: I now use the following puppet-lint configuration in my Rakefile:

    Rake::Task[:lint].clear
    PuppetLint::RakeTask.new :lint do |config|
      config.disable_checks = [ 
        '80chars',
        'class_parameter_defaults',
        'class_inherits_from_params_class'
      ]
      config.log_format = "%{path}:%{linenumber}:%{check}:%{KIND}:%{message}"
      config.fail_on_warnings = true
      #config.relative = true

      config.ignore_paths = exclude_paths
    end

This should lead to an equivalent configuration as in revision f7619710750346e83f4826eb7f695bb1dc5541a9, except that I have commented out the `config.relative = true` statement, since it does not work for me:

    evevm023:~/my-module$ bundle exec rake lint
    rake aborted!
    NoMethodError: undefined method `relative=' for #<PuppetLint::RakeTask:0x0000000272ba58>
    /home/fox056o/Projects/Phoenix/puppet/gns-samba/Rakefile:27:in `block in <top (required)>'
    /home/fox056o/Projects/Phoenix/puppet/gns-samba/vendor/bundle/ruby/1.9.1/gems/puppet-lint-1.1.0/lib/puppet-lint/tasks/puppet-lint.rb:50:in `call'
    /home/fox056o/Projects/Phoenix/puppet/gns-samba/vendor/bundle/ruby/1.9.1/gems/puppet-lint-1.1.0/lib/puppet-lint/tasks/puppet-lint.rb:50:in `define'
    /home/fox056o/Projects/Phoenix/puppet/gns-samba/vendor/bundle/ruby/1.9.1/gems/puppet-lint-1.1.0/lib/puppet-lint/tasks/puppet-lint.rb:44:in `initialize'
    /home/fox056o/Projects/Phoenix/puppet/gns-samba/Rakefile:19:in `new'
    /home/fox056o/Projects/Phoenix/puppet/gns-samba/Rakefile:19:in `<top (required)>'
    (See full trace by running task with --trace)

**Comment by fatmcgav** [comment]
The relative issue was fixed in https://github.com/rodjek/puppet-lint/commit/e6e0d4fd1ab0fb6415e5ade0958210ad944b0087

**Comment by garethr** [comment]
Thanks, this should now be fixed, https://github.com/garethr/puppet-module-skeleton/commit/28d4e2176a44f3296f79d2636eecee4a69d5ba6e.
