### ISSUE TITLE
Contributing guide confuses unit and integration tests

### ISSUE THREAD

**Issue by rnelson0** [garethr/puppet-module-skeleton#47]
See https://github.com/garethr/puppet-module-skeleton/blob/master/skeleton/CONTRIBUTING.md#automatically-run-the-integration-tests. The section title says integration tests but the section text says unit tests. I'm not knowledgeable enough to know the difference and submit a PR so I opened an issue. I noticed in https://github.com/electrical/puppet-beaver/pull/17/files#diff-6a3371457528722a734f3c51d9238c13R62 where this skeleton was used to populate that module.

**Comment by garethr** [comment]
@rnelson0 thanks for letting me know, should now be fixed in master
