### ISSUE TITLE
Vagrant command not found

### ISSUE THREAD

**Issue by jonmosco** [garethr/puppet-module-skeleton#49]
I am getting the following error when trying to run the beaker tests:

bundle exec rspec spec/acceptance
Hypervisor for centos-64-x64 is vagrant
Beaker::Hypervisor, found some vagrant boxes to create
/Users/jmosco/.rvm/gems/ruby-2.0.0-p598@beaker_2_0/gems/beaker-2.1.0/lib/beaker/hypervisor/vagrant.rb:166:in `block (2 levels) in vagrant_cmd': Failed to exec 'vagrant destroy --
force' (RuntimeError)
        from /Users/jmosco/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/open3.rb:217:in `popen_run'
        from /Users/jmosco/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/open3.rb:99:in `popen3'
        from /Users/jmosco/.rvm/gems/ruby-2.0.0-p598@beaker_2_0/gems/beaker-2.1.0/lib/beaker/hypervisor/vagrant.rb:161:in `block in vagrant_cmd'
        from /Users/jmosco/.rvm/gems/ruby-2.0.0-p598@beaker_2_0/gems/beaker-2.1.0/lib/beaker/hypervisor/vagrant.rb:159:in `chdir'
        from /Users/jmosco/.rvm/gems/ruby-2.0.0-p598@beaker_2_0/gems/beaker-2.1.0/lib/beaker/hypervisor/vagrant.rb:159:in `vagrant_cmd'
        from /Users/jmosco/.rvm/gems/ruby-2.0.0-p598@beaker_2_0/gems/beaker-2.1.0/lib/beaker/hypervisor/vagrant.rb:117:in `provision'
        from /Users/jmosco/.rvm/gems/ruby-2.0.0-p598@beaker_2_0/gems/beaker-2.1.0/lib/beaker/hypervisor.rb:68:in `create'
        from /Users/jmosco/.rvm/gems/ruby-2.0.0-p598@beaker_2_0/gems/beaker-2.1.0/lib/beaker/network_manager.rb:48:in `block in provision'
        from /Users/jmosco/.rvm/gems/ruby-2.0.0-p598@beaker_2_0/gems/beaker-2.1.0/lib/beaker/network_manager.rb:47:in `each_key'
        from /Users/jmosco/.rvm/gems/ruby-2.0.0-p598@beaker_2_0/gems/beaker-2.1.0/lib/beaker/network_manager.rb:47:in `provision'
        from /Users/jmosco/.rvm/gems/ruby-2.0.0-p598@beaker_2_0/gems/beaker-rspec-4.0.0/lib/beaker-rspec/beaker_shim.rb:29:in `provision'
        from /Users/jmosco/.rvm/gems/ruby-2.0.0-p598@beaker_2_0/gems/beaker-rspec-4.0.0/lib/beaker-rspec/spec_helper.rb:40:in `block in <top (required)>'
        from /Users/jmosco/.rvm/gems/ruby-2.0.0-p598@beaker_2_0/gems/rspec-core-2.99.2/lib/rspec/core.rb:154:in `configure'
        from /Users/jmosco/.rvm/gems/ruby-2.0.0-p598@beaker_2_0/gems/beaker-rspec-4.0.0/lib/beaker-rspec/spec_helper.rb:5:in `<top (required)>'
        from /Users/jmosco/projects/puppet/modules/a-ntp/spec/spec_helper_acceptance.rb:1:in `require'
        from /Users/jmosco/projects/puppet/modules/a-ntp/spec/spec_helper_acceptance.rb:1:in `<top (required)>'
        from /Users/jmosco/projects/puppet/modules/a-ntp/spec/acceptance/class_spec.rb:1:in `require'
        from /Users/jmosco/projects/puppet/modules/a-ntp/spec/acceptance/class_spec.rb:1:in `<top (required)>'
        from /Users/jmosco/.rvm/gems/ruby-2.0.0-p598@beaker_2_0/gems/rspec-core-2.99.2/lib/rspec/core/configuration.rb:1065:in `load'
        from /Users/jmosco/.rvm/gems/ruby-2.0.0-p598@beaker_2_0/gems/rspec-core-2.99.2/lib/rspec/core/configuration.rb:1065:in `block in load_spec_files'
        from /Users/jmosco/.rvm/gems/ruby-2.0.0-p598@beaker_2_0/gems/rspec-core-2.99.2/lib/rspec/core/configuration.rb:1065:in `each'
        from /Users/jmosco/.rvm/gems/ruby-2.0.0-p598@beaker_2_0/gems/rspec-core-2.99.2/lib/rspec/core/configuration.rb:1065:in `load_spec_files'
        from /Users/jmosco/.rvm/gems/ruby-2.0.0-p598@beaker_2_0/gems/rspec-core-2.99.2/lib/rspec/core/command_line.rb:18:in `run'
        from /Users/jmosco/.rvm/gems/ruby-2.0.0-p598@beaker_2_0/gems/rspec-core-2.99.2/lib/rspec/core/runner.rb:103:in `run'
        from /Users/jmosco/.rvm/gems/ruby-2.0.0-p598@beaker_2_0/gems/rspec-core-2.99.2/lib/rspec/core/runner.rb:17:in `block in autorun'

This is with a base module generate and accepting all the defaults.  RVM environment tested with Ruby 2.0 and 2.1.  

Vagrant is installed and has been tested:

vagrant --version
Vagrant 1.7.1

**Comment by garethr** [comment]
Vagrant changed how it uses the ssh key which broke Beaker. It's fixed in the latest version. https://github.com/puppetlabs/beaker/pull/586 in master.

I'll keep an eye on that issue, for the moment you can replace the beaker line with:

    gem "beaker", :git => 'https://github.com/puppetlabs/beaker.git'

Then `bundle update beaker beaker-rspec`.

**Comment by jonmosco** [comment]
Excellent,  thank you.  I also discovered that the skeleton uses virtualbox
as the provider which caused problems when using fusion.  When I changed
the nodesets to use a fusion box, the environment booted no problem.

**Comment by garethr** [comment]
The latest version of beaker now has the fix for this. https://github.com/puppetlabs/beaker/releases/tag/beaker2.2.0

Thanks again for flagging.
