### ISSUE TITLE
rspec-puppet 2.0 causes dependency issues

### ISSUE THREAD

**Issue by SmegTheLight** [garethr/puppet-module-skeleton#51]
Not well versed with things 'ruby', but trying to get your skeleton working and having an issue.  I installed on clean environment to make sure it was not some other garbage I had.
After digging around, it looks like rspec-puppet pulled in from rodjek github repo is specifying some dependencies that is conflicting with the Gemfile in the Skeleton.

bundler install throws :
<code>
Bundler could not find compatible versions for gem "rspec":
  In Gemfile:
    rspec-puppet (>= 0) ruby depends on
      rspec (~> 2.0) ruby

    beaker-rspec (>= 0) ruby depends on
      rspec (3.1.0)
</code>
rspec-puppet recently released 2.0.0 as master, so that probably is where the issue started.

I changed the Gemfile entry to set the v1.0.1 tag, and now bundle install works.
<code>
gem "rspec-puppet", :git => 'https://github.com/rodjek/rspec-puppet.git', :tag => 'v1.0.1'
</code>

**Comment by tuxmea** [comment]
Which version of ruby are you using?

**Comment by SmegTheLight** [comment]
ruby 1.9.3p194 (Ubuntu/Debian stock)

**Comment by garethr** [comment]
Note that I recently setup Travis builds for this repo which should help catch issues like this in the future. In fact the build broke a few days ago (and if now fixed) due to a transient dependency issue like this. The dependencies should be working now.
