### ISSUE TITLE
Issue with puppet-blacksmith and metadata-json-lint

### ISSUE THREAD

**Issue by thejandroman** [garethr/puppet-module-skeleton#52]
Looks like an issue between metadata-json-lint and puppet are causing issues with puppet-blacksmith. More information at maestrodev/puppet-blacksmith#14 and nibalizer/metadata-json-lint#10.

**Comment by garethr** [comment]
Thanks for flagging this. I think the explicit call to 'puppet/vendor/semantic/lib/semantic' before loading these should solve the issue (from reading the issues and a quick bit of testing).

https://github.com/garethr/puppet-module-skeleton/commit/28d4e2176a44f3296f79d2636eecee4a69d5ba6e
