### ISSUE TITLE
metadata-json-lint complaining about default license 'Apache 2.0'

### ISSUE THREAD

**Issue by rauchrob** [garethr/puppet-module-skeleton#62]
After generating a new module and accepting the default license, `metadata-json-lint` complains about 'Apache 2.0' not being in the SPDX list (http://spdx.org/licenses). Apparently, one should use 'Apache-2.0' as license string instead. Or is this a Bug in Puppet?

**Comment by rauchrob** [comment]
I see this has already been adressed in f74f320497fa5a2b0e821dcb028413aa4c4472fb...

**Comment by garethr** [comment]
You're correct, this is a big in Puppet. It's been fixed in master and will be correct in 4.0: https://tickets.puppetlabs.com/browse/PUP-3894

The workaround you point to is just for the CI builds for the skeleton, for your own module you can provide a valid license string. 

Thanks for noticing.
