### ISSUE TITLE
lint is ignored by default

### ISSUE THREAD

**Issue by mkrakowitzer** [garethr/puppet-module-skeleton#75]
When using this module skeleton, if I add a lint error to the manifests/init.pp it does not report an error or warning.
```
$ bundle exec rake lint
$ echo $?
0
```
when I run `rake test`, it also just not report an error and exits 0.

When I remove `Rake::Task[:lint].clear` from the Rakefile, It now reports lint errors.

```
bundle exec rake lint
manifests/init.pp:16:nested_classes_or_defines:WARNING:defined type defined inside a class
```

I am not sure if this is the desired behavior or if I am just doing something wrong.

**Comment by garethr** [comment]
This should be resolved at this point. The Rakefile was clearing the default task but never actually recreating it.
