### ISSUE TITLE
Running bundle exec rake coverage fails on bare skeleton

### ISSUE THREAD

**Issue by Rovanion** [garethr/puppet-module-skeleton#96]
The following is from a bare repo generated from the skeleton:

```stacktrace
$ bundle exec rake coverage --trace
** Invoke coverage (first_time)
** Execute coverage
rake aborted!
NoMethodError: undefined method `rcov=' for #<RSpec::Core::RakeTask:0x8b13c14>
/var/lib/gems/1.9.1/gems/puppetlabs_spec_helper-1.0.1/lib/puppetlabs_spec_helper/rake_tasks.rb:21:in `block in <top (required)>'
/var/lib/gems/1.9.1/gems/rspec-core-3.1.7/lib/rspec/core/rake_task.rb:108:in `call'
/var/lib/gems/1.9.1/gems/rspec-core-3.1.7/lib/rspec/core/rake_task.rb:108:in `block (2 levels) in define'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/file_utils_ext.rb:58:in `verbose'
/var/lib/gems/1.9.1/gems/rspec-core-3.1.7/lib/rspec/core/rake_task.rb:107:in `block in define'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/var/lib/gems/1.9.1/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => coverage
```

From what I managed to google the solution should be to sprinkle ```require 'rspec'``` into some related file. But I'm not familiar with rspec so I tried putting it in every file which could be related to coverage under ```./spec/```, but to no avail.

**Comment by garethr** [comment]
Mmm, yeah. the coverage task is part of puppetlabs-spec-helper, and probably should be removed from there. The error you're seeng is because rcov doesn't exist for Ruby 1.9.2. I might just hide that command from upstream.

Note that this command isn't required. For ruby coverage you should get that from https://github.com/garethr/puppet-module-skeleton/blob/master/skeleton/spec/spec_helper.rb#L6-L16. For Puppet code coverage you should get that from https://github.com/garethr/puppet-module-skeleton/blob/master/skeleton/spec/classes/coverage_spec.rb.

**Comment by garethr** [comment]
Removed in https://github.com/garethr/puppet-module-skeleton/commit/ff4195ae6bb80bf4b6a9d658eeb2b41f144d5408

**Comment by Rovanion** [comment]
So am I reading you right if I think you're saying that the coverage commands are nowadays build in to some other rake task? And that the ```rake coverage``` command has been redundant for some time, and because of that never really tested?

**Comment by garethr** [comment]
The coverage command comes in automatically from the puppetlabs-spec-helper dependency. It works, but only under older versions of Ruby. At least for this skeleton it's not required as other coverage options are supported.

**Comment by Rovanion** [comment]
I think I grok now. Thank you for your kind help!
